### ISSUE TITLE
Add additional info to README + CONTRIBUTING

### ISSUE THREAD

**Issue by gothfemme** [d2foundry/oracle_engine#27]
Now that the repo's public we should add some additional docs around guidelines for contributing and other top of mind info for developing in it.

- Add `CONTRIBUTING.md`
- Link to it from `README.md`
- Fill both out with some info that seems relevant

**Comment by JayAndromeda** [comment]
Created PR: https://github.com/d2foundry/oracle_engine/pull/32 for this. Might still adjust the README.md as I can see how it has a weird flow.
